// File: Employee.cs
using System;

namespace employee_management_system
{
    public class Employee
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }

        // Constructor for creating a new employee (ID will be generated by DB)
        public Employee() { }

        // Constructor for an existing employee
        public Employee(int id, string name, string role, string email, string phoneNumber)
        {
            EmployeeId = id;
            Name = name;
            Role = role;
            Email = email;
            PhoneNumber = phoneNumber;
        }
    }
}